# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MQ-ESOJqExVKLAvB3Z2qJ17HK8EV6WLT
"""

import requests
import pandas as pd
import streamlit as st

# 気象庁APIのエリアコード
area_codes = {
    "東京": "130000",
    "大阪": "270000",
    "名古屋": "230000"
}

# 天気データ取得関数
def get_weather_data(area_code):
    url = f"https://www.jma.go.jp/bosai/forecast/data/forecast/{area_code}.json"
    response = requests.get(url)
    data = response.json()

    weather_data = []
    for i in range(len(data[0]["timeSeries"][0]["timeDefines"])):
        day = data[0]["timeSeries"][0]["timeDefines"][i]
        weather = data[0]["timeSeries"][0]["areas"][0]["weathers"][i]
        weather_data.append({"日付": day, "天気": weather})

    return pd.DataFrame(weather_data)

# Streamlit UI
st.title("地域選択付き天気フィルターアプリ")

# 地域選択
selected_area = st.selectbox("地域を選択してください", list(area_codes.keys()))

# 天気データ取得
df = get_weather_data(area_codes[selected_area])

# フィルター機能
if st.button("晴れの日"):
    st.write(df[df["天気"].str.contains("晴れ")]["日付"].tolist())

if st.button("雨の日"):
    st.write(df[df["天気"].str.contains("雨")]["日付"].tolist())

if st.button("曇りの日"):
    st.write(df[df["天気"].str.contains("曇り")]["日付"].tolist())

